name: Test

on: [push]

jobs:
  test:
    name: Test

    runs-on: ubuntu-latest

    strategy:
      matrix:
#        php-version: ['7.1', '7.2', '7.3', '7.4', '8.0']
        php-version: ['8.0']

    steps:
      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: echo
        run: php -i
